### ISSUE TITLE
Yesno value is shown as {1|0} rather than given strings

### ISSUE THREAD

**Issue by iainhallam** [rendezz/dokuwiki-pagemod#38]
I'm using pagemod for a simple form:

```
<form>
action mail XXXX
thanks "Thanks for recording your agreement"

fieldset "Agreement"
yesno "I AGREE" "=Agree" "!Disagree"

submit "Submit"
</form>
```

This is working fine, and I can get an email with the contents "I AGREE Agree".

If I replace the action with:

```
action pagemod :agreements agreement
```

Where `:agreements` contains:

```
<pagemod agreement>|[[@@meta.user.mail@@|@@meta.user.id@@ (@@meta.user.name@@)]]|@@meta.datetime@@|@@I AGREE@@|
</pagemod>
```

Then the I AGREE field only has 1 or 0, not Agree or Disagree.

**Comment by Klap-in** [comment]
Is this related: https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/pull/234

**Comment by iainhallam** [comment]
Looks about right :)
